### ISSUE TITLE
Every Time At the time of Launch : NSWindow warning: adding an unknown subview:

### ISSUE THREAD

**Issue by praveen27Kmr** [indragiek/INAppStoreWindow#208] opened 2016-09-05 04:42 UTC
NSWindow warning: adding an unknown subview: <INTitlebarContainer: 0x608000122da0>
2016-09-05 10:10:36.614 <APP-NAME>[548:6417] Call stack:
(
    0   AppKit                              0x00007fff9324454d -[NSThemeFrame addSubview:] + 107
    1   AppKit                              0x00007fff9324403f -[NSView addSubview:positioned:relativeTo:] + 208
    2   Advanced Password Manager           0x000000010003252c -[INAppStoreWindow _createTitlebarView] + 252
    3   Advanced Password Manager           0x0000000100031210 -[INAppStoreWindow _doInitialWindowSetup] + 992
    4   Advanced Password Manager           0x000000010002f867 -[INAppStoreWindow initWithContentRect:styleMask:backing:defer:] + 167
    5   AppKit                              0x00007fff9322e9d3 -[NSWindowTemplate nibInstantiate] + 567
    6   AppKit                              0x00007fff9322e71b -[NSIBObjectData instantiateObject:] + 309
    7   AppKit                              0x00007fff9322dd41 -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 452
    8   AppKit                              0x00007fff9320d0e5 loadNib + 384
    9   AppKit                              0x00007fff9320c60b +[NSBundle(NSNibLoading) _loadNibFile:nameTable:options:withZone:ownerBundle:] + 313
    10  AppKit                              0x00007fff9320c3c7 -[NSBundle(NSNibLoading) loadNibNamed:owner:topLevelObjects:] + 201
    11  AppKit                              0x00007fff9320c193 +[NSBundle(NSNibLoading) loadNibNamed:owner:] + 344
    12  AppKit                              0x00007fff93204d79 NSApplicationMain + 605
    13  Advanced Password Manager           0x0000000100005e66 main + 470
    14  libdyld.dylib                       0x00007fff88c5c5c9 start + 1
)

**Comment by praveen27Kmr** [comment] 2016-09-09 04:45
@indragiek

**Comment by indragiek** [comment] 2016-09-27 05:14
Known bug in OS X 10.10+, there is no current workaround. Duplicate of #169

**Closed as completed by indragiek** 2016-09-27 05:14 UTC
